site_name: Vectorlab SGI
site_description: Sistema di Gestione Integrato - Documentazione ISO
theme:
  name: material
  language: it
  features:
    - navigation.sections
    - navigation.expand
    - search.suggest
    - content.code.copy
docs_dir: docs
